-- Replace cost categories with BCRE Spread_Detailed taxonomy
DELETE FROM cost_categories;
INSERT INTO cost_categories (category_name, csi_division, sort_order) VALUES
  ('Survey/Staking', '02', 1),
  ('Erosion&Sedimentation Control', '02', 2),
  ('Site Demolition', '02', 3),
  ('Flatwork', '03', 4),
  ('Pool/Spa Concrete Decking', '03', 5),
  ('Concrete - Foundations', '03', 6),
  ('Concrete - Foundations - Amenity', '03', 7),
  ('Lightweight Concrete', '03', 8),
  ('Concrete Unit Masonry', '04', 9),
  ('Handrails - Site', '05', 10),
  ('Handrails - Buildings', '05', 11),
  ('Metal Specialties', '05', 12),
  ('Ornamental Iron', '05', 13),
  ('Miscellaneous Steel', '05', 14),
  ('Rough Carpentry', '06', 15),
  ('Rough Carpentry - Amenity', '06', 16),
  ('Finish Carpentry', '06', 17),
  ('Finish Carpentry - Amenity', '06', 18),
  ('Deck Coatings (Buildings)', '07', 19),
  ('Deck Coatings (Amenity Bldg)', '07', 20),
  ('Insulation (Buildings)', '07', 21),
  ('Insulation (Amenity Bldg)', '07', 22),
  ('Waterproofing', '07', 23),
  ('Masonry Wall Waterproofing', '07', 24),
  ('Roofing', '07', 25),
  ('Sheet Metal Flashing & Trim (Buildings)', '07', 26),
  ('Sheet Metal Flashing & Trim (Amenity Bldg)', '07', 27),
  ('Firestopping', '07', 28),
  ('Access Panels (Buildings)', '08', 29),
  ('Access Panels (Amenity Bldg)', '08', 30),
  ('Doors - Roll Up (Buildings)', '08', 31),
  ('Doors - Roll Up (Amenity Bldg)', '08', 32),
  ('Entry Gates', '08', 33),
  ('Entry Gates - Operators&Loops', '08', 34),
  ('Storefronts (Buildings)', '08', 35),
  ('Storefronts (Amenity Bldg)', '08', 36),
  ('Vinyl Windows (Buildings)', '08', 37),
  ('Vinyl Windows (Amenity Bldg)', '08', 38),
  ('Glass and Glazing', '08', 39),
  ('Mirrors and Shower Doors', '08', 40),
  ('Mirrors', '08', 41),
  ('Rough Clean (Buildings)', '09', 42),
  ('Rough Clean (Amenity Bldg)', '09', 43),
  ('Final Clean/Move-in (Buildings)', '09', 44),
  ('Final Clean/Move-in (Amenity Bldg)', '09', 45),
  ('Drywall (Buildings)', '09', 46),
  ('Drywall (Amenity Bldg)', '09', 47),
  ('Cement Stucco (Buildings)', '09', 48),
  ('Cement Stucco (Amenity Bldg)', '09', 49),
  ('Amenity Tile', '09', 50),
  ('Interior Tiling', '09', 51),
  ('Specialty Flooring', '09', 52),
  ('Resilient Flooring - Common', '09', 53),
  ('Resilient Flooring - Units', '09', 54),
  ('Carpeting', '09', 55),
  ('Painting - Units (Buildings)', '09', 56),
  ('Painting - Units (Amenity Bldg)', '09', 57),
  ('Signage', '10', 58),
  ('Entry Monument', '10', 59),
  ('Glass Shower & Bath Enclosures', '10', 60),
  ('Toilet Partition/Bath Access (Buildings)', '10', 61),
  ('Toilet Partition/Bath Access (Amenity Bldg)', '10', 62),
  ('Fire Extinguishers', '10', 63),
  ('Mail Boxes', '10', 64),
  ('Fireplace (Amenity)', '10', 65),
  ('Residential Appliances', '11', 66),
  ('Amenity Appliances', '11', 67),
  ('Barbeque Equipment', '11', 68),
  ('Window Treatments', '12', 69),
  ('Cabinets (Buildings)', '12', 70),
  ('Cabinets (Amenity Bldg)', '12', 71),
  ('Countertops - Baths', '12', 72),
  ('Countertops', '12', 73),
  ('Bicycle Racks', '12', 74),
  ('Trash and Litter Receptacles', '12', 75),
  ('Site Furnishings', '12', 76),
  ('Swimming Pool', '13', 77),
  ('Fire Systems Waterline', '21', 78),
  ('Fire Sprinklers (Buildings)', '21', 79),
  ('Fire Sprinklers (Amenity Bldg)', '21', 80),
  ('Plumbing (Buildings)', '22', 81),
  ('Plumbing (Amenity Bldg)', '22', 82),
  ('HVAC (Buildings)', '23', 83),
  ('HVAC (Amenity Bldg)', '23', 84),
  ('Electrical Wiring (Buildings)', '26', 85),
  ('Electrical Wiring (Amenity Bldg)', '26', 86),
  ('Photovoltaic System', '26', 87),
  ('Elec Fixtures - Living Area', '26', 88),
  ('Elec Fixtures - Building (Buildings)', '26', 89),
  ('Elec Fixtures - Building (Amenity Bldg)', '26', 90),
  ('Lighting - Offsite', '26', 91),
  ('Ext Site Lighting-Fixtures', '26', 92),
  ('Ext Site Lighting-Install', '26', 93),
  ('Voice/Data/Network Systems', '27', 94),
  ('Audio-Video Devices', '27', 95),
  ('Access Control System', '28', 96),
  ('Access Control Police/Fire', '28', 97),
  ('Live Security', '28', 98),
  ('Security Cameras', '28', 99),
  ('Fire Alarm (Buildings)', '28', 100),
  ('Fire Alarm (Amenity Bldg)', '28', 101),
  ('Grading', '31', 102),
  ('Erosion & Sediment Controls', '31', 103),
  ('Soil Treatment', '31', 104),
  ('Traffic Control', '32', 105),
  ('Landscape Maintenance', '32', 106),
  ('Street Improvements', '32', 107),
  ('Asphalt Paving', '32', 108),
  ('Asphalt Paving - Site', '32', 109),
  ('Concrete Unit Pavers', '32', 110),
  ('Pavement Markings/Street Signs', '32', 111),
  ('Fencing & Gates', '32', 112),
  ('Fencing - Masonry - Site', '32', 113),
  ('Landscape & Irrigation', '32', 114),
  ('Domestic Water', '33', 115),
  ('Sanitary Sewer', '33', 116),
  ('Storm Drain', '33', 117),
  ('Other Utilities Trench & Dist', '33', 118);